[package]
name = "patch_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/patch_ui.rs"


[dependencies]
gpui.workspace = true
ui.workspace = true
workspace.workspace = true
